In [ ]:
import numpy as np
import torch

In [ ]:
torch.__version__

'2.4.1+cu121'

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
x = torch.from_numpy(arr)

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
type(x)

torch.Tensor

In [ ]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
x.dtype

torch.int64

In [ ]:
arr_2d = np.arange(0.0,12.0)

In [ ]:
arr_2d = arr_2d.reshape(4,3)

In [ ]:
arr_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr_2d)

In [ ]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
arr[0] = 99

In [ ]:
arr

array([99,  2,  3,  4,  5])

In [ ]:
x

tensor([99,  2,  3,  4,  5])

In [ ]:
my_arr = np.arange(0,10)

In [ ]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor = torch.tensor(my_arr)

In [ ]:
my_other_tensor = torch.from_numpy(my_arr)

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_arr[0] = 9999

In [ ]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new_arr = np.array([1,2,3])

In [ ]:
new_arr.dtype

dtype('int64')

In [ ]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [ ]:
my_tensor = torch.Tensor(new_arr)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
torch.empty(4,2)

tensor([[4.2043e-04, 4.3879e-41],
        [4.2043e-04, 4.3879e-41],
        [1.2348e-39, 2.9829e-30],
        [2.5353e+30, 2.1019e-44]])

In [ ]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
my_tensor = torch.tensor([1,2,3])

In [ ]:
my_tensor.dtype

torch.int64

In [ ]:
my_tensor = my_tensor.type(torch.int32)

In [ ]:
my_tensor.dtype

torch.int32

In [ ]:
torch.rand(4,3)

tensor([[0.1426, 0.9282, 0.0192],
        [0.9898, 0.9665, 0.3458],
        [0.5985, 0.2285, 0.1448],
        [0.2033, 0.7369, 0.4295]])

In [ ]:
torch.randn(4,3)

tensor([[-0.8074, -0.0725,  0.0278],
        [ 0.2521,  1.1308, -0.8280],
        [-1.0139, -1.3491,  1.0304],
        [ 2.2938, -0.6810, -1.0887]])

In [ ]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[ 1,  5,  6,  7,  8],
        [10,  7,  2, 10,  2],
        [ 9,  9,  1,  9,  0],
        [ 6,  9,  2,  4,  0],
        [ 5,  8,  8,  7, 10]])

In [ ]:
x = torch.zeros(2,5)

In [ ]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
torch.rand_like(x)

tensor([[0.8057, 0.3702, 0.7798, 0.6521, 0.1239],
        [0.6179, 0.2028, 0.2055, 0.2066, 0.7568]])

In [ ]:
torch.randn_like(x)

tensor([[-0.5638, -0.1257,  1.0241, -1.6791, -0.4501],
        [-0.4972, -0.8272,  1.0659, -0.5025,  0.6158]])

In [ ]:
torch.randint_like(x,low=0,high=11)

tensor([[3., 3., 6., 9., 3.],
        [2., 4., 6., 9., 4.]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])