In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.arange(6).reshape(3,2)

In [ ]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
x[1,1]

tensor(3)

In [ ]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [ ]:
x = torch.arange(0,10)

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = x.reshape(2,5)

In [ ]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x = torch.arange(0,10)

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

torch.Size([10])

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = x.view(2,5)

In [ ]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x[0] = 9999

In [ ]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
x = torch.arange(10)

In [ ]:
x.shape

torch.Size([10])

In [ ]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a = torch.tensor([1.,2.,3.])

In [ ]:
b = torch.tensor([4.,5.,6.])

In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
a.dtype

torch.float32

In [ ]:
a + b

tensor([5., 7., 9.])

In [ ]:
torch.add(a,b)

tensor([5., 7., 9.])

In [ ]:
a.mul(b)

tensor([ 4., 10., 18.])

In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [ ]:
a

tensor([ 4., 10., 18.])

In [ ]:
a = torch.tensor([1.,2.,3.])

In [ ]:
a * b

tensor([ 4., 10., 18.])

In [ ]:
a.mul(b)

tensor([ 4., 10., 18.])

In [ ]:
a.dot(b)

tensor(32.)

In [ ]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [ ]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [ ]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
b.shape

torch.Size([3, 2])

In [ ]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [ ]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [ ]:
x = torch.tensor([2.,3.,4.,5.])

In [ ]:
x

tensor([2., 3., 4., 5.])

In [ ]:
x.norm()

tensor(7.3485)

In [ ]:
x.numel()

4

In [ ]:
len(x)

4

In [ ]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
len(a)

2

In [ ]:
a.numel()

6